Fix HTML conversion

diff --git a/.workflows/github/eval_pub.yaml b/.workflows/github/eval_pub.yaml
--- a/.workflows/github/eval_pub.yaml
+++ b/.workflows/github/eval_pub.yaml
@@ -20,11 +20,11 @@ jobs:
         run: bash -c "conda init bash"
       - name: Run all notebooks with papermill
         run: |
-          bash -c ". ${HOME}/.bashrc && conda activate notebook && .ci/run_all_notebooks.py --dir . --out ci_out/"
+          bash -c ". ${HOME}/.bashrc && conda activate notebook && .ci/run_all_notebooks.py --dir . --out ci_out/" || echo "failed"
       - name: Convert to HTML
         if: ${{ always() }}
         run: |
-          bash -c '. ${HOME}/.bashrc && conda activate notebook && cd ci_out/ && ls -1 *.ipynb | xargs -n1 -P4 -I {} jupyter nbconvert --to HTML {}'
+          bash -c ". ${HOME}/.bashrc && conda activate notebook && cd ci_out/ && ls -1 *.ipynb | xargs -n1 -P4 -I {} jupyter nbconvert --to HTML {}"
       - name: Upload notebook
         uses: actions/upload-artifact@v1
         if: ${{ always() }}
