Fix workflow path (also again.)

diff --git a/.github/workflows/eval_pub.yaml b/.github/workflows/eval_pub.yaml
--- a/.github/workflows/eval_pub.yaml
+++ b/.github/workflows/eval_pub.yaml
@@ -20,7 +20,11 @@ jobs:
         run: bash -c "conda init bash"
       - name: Run all notebooks with papermill
         run: |
-          bash -c ". ${HOME}/.bashrc && conda activate notebook && .ci/run_all_notebooks.py --dir . --out ci_out/"
+          bash -c ". ${HOME}/.bashrc && conda activate notebook && .ci/run_all_notebooks.py --dir . --out ci_out/" || echo "failed"
+      - name: Convert to HTML
+        if: ${{ always() }}
+        run: |
+          bash -c ". ${HOME}/.bashrc && conda activate notebook && cd ci_out/ && jupyter nbconvert --to HTML \*.ipynb"
       - name: Upload notebook
         uses: actions/upload-artifact@v1
         if: ${{ always() }}
